quarkus.http.port=9000


quarkus.cxf.codegen.wsdl2java.includes = wsdl/*.wsdl

calculator.baseUri=http://localhost:8080
quarkus.cxf.client.myCalculator.wsdl = ${calculator.baseUri}/calculator-ws/CalculatorService?wsdl
quarkus.cxf.client.myCalculator.client-endpoint-url = ${calculator.baseUri}/calculator-ws/CalculatorService
quarkus.cxf.client.myCalculator.service-interface = org.jboss.eap.quickstarts.wscalculator.calculator.CalculatorService
quarkus.cxf.logging.enabled = true
quarkus.cxf.logging.pretty = true



verificaContaCpfTitularidade.baseUri=https://cicsweb.des.caixa:32587
quarkus.cxf.client.verificaContaCpfTitularidade.wsdl = ${verificaContaCpfTitularidade.baseUri}/sid09/verificaContaCpfTitularidade?wsdl
quarkus.cxf.client.verificaContaCpfTitularidade.client-endpoint-url = ${verificaContaCpfTitularidade.baseUri}/sid09/verificaContaCpfTitularidade
quarkus.cxf.client.verificaContaCpfTitularidade.service-interface =br.gov.caixa.sid09.verificacontacpftitularidade.D09POVTFPort
quarkus.cxf.client.verificaContaCpfTitularidade.username=c079563
quarkus.cxf.client.verificaContaCpfTitularidade.password=R23apolo
quarkus.cxf.client.verificaContaCpfTitularidade.secure-wsdl-access = true
quarkus.cxf.endpoint.verificaContaCpfTitularidade.security.disable.require.client.cert.check=true

keystore.type = jks
quarkus.cxf.verificaContaCpfTitularidade.client-endpoint-url = ${verificaContaCpfTitularidade}
quarkus.cxf.verificaContaCpfTitularidade.service-interface = io.quarkiverse.cxf.it.security.policy.HelloService
quarkus.cxf.verificaContaCpfTitularidade.trust-store-type = ${keystore.type}
quarkus.cxf.verificaContaCpfTitularidade.trust-store = client-truststore.${keystore.type}
quarkus.cxf.verificaContaCpfTitularidade.trust-store-password = password
