diretorioEntrada=src/test/resources/insumos/entrada
diretorioSaida=src/test/resources/insumos/saida





xpathStatus=//pedido/pagamento/status/text()
xpathTitular=//pedido/pagamento/titular/text()
xpathEmailTitular=//pedido/pagamento/email-titular/text()
xpathIdPedido=//pedido/id/text()
urlApi=http://localhost:8080