quarkus.datasource.db-kind=postgresql
quarkus.datasource.db-version = 15.0 

quarkus.datasource.username=appuser
quarkus.datasource.password=apppass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/basegenerica
quarkus.datasource.jdbc.max-size=16
quarkus.datasource.reactive.url=postgresql://appuser:apppass@localhost:5432/basegenerica
quarkus.datasource.reactive.max-size=16
quarkus.datasource.devservices.enabled=false
quarkus.http.test-port=8089